### ISSUE TITLE
Eq. 6 in paper

### ISSUE THREAD

**Issue by YuLin-Cheng** [lartpang/MINet#1]
what does the abbrev "sup(g -pg)" stand for  in eq. 6? supremum?

thanks
![eq6](https://user-images.githubusercontent.com/61443724/82834964-3f09bb80-9ef5-11ea-92d0-814dd2410c05.PNG)

**Comment by lartpang** [comment]
It is a clerical error. It should be `\sum(g-pg)`.

![image](https://user-images.githubusercontent.com/26847524/82856461-96814900-9f40-11ea-851e-852a2f968256.png)

**Comment by YuLin-Cheng** [comment]
obviously 
thank you anyway
and it's a nice paper and implementation
