### ISSUE TITLE
How does WSGN improve the generalization performance of the model

### ISSUE THREAD

**Issue by michael861227** [lartpang/MINet#10]
Hi, thanks for your great work, I have trained the model using CPLMINet_WSGNRes50 network on other datasets, and found it really improves the generalization performance on the evaluation score compared to origin MINet network .

I'm curious is WSGN only change the backbone from the origin MINet network, or is there anything I have missed, and wonder know is it the main reason to improve generalization performance of the model?

**Comment by lartpang** [comment]
@michael861227 
> I'm curious is WSGN only change the backbone from the origin MINet network, or is there anything I have missed, and wonder know is it the main reason to improve generalization performance of the model?
WSGN is from the paper: https://arxiv.org/abs/1903.10520
And it is also recommended for transfer learning in this paper: https://arxiv.org/abs/1912.11370
It is an effective improvement strategy for group normalization, and it can improve the generalization ability and the performance of MINet.

So, for your problem, I think it should be the promotion it brought. 
It is a common phenomenon that better backbone can effectively improve the effect of segmentation.

**Comment by michael861227** [comment]
Thank you! I think it may be help to my problem.
