### ISSUE TITLE
DataSet Split

### ISSUE THREAD

**Issue by Dreamerswile** [lartpang/MINet#12]
您好，请问您如何对PASCAL-S，HKU-IS等数据集是如何划分训练集和测试集的呢？我找到的这些数据集，除了DUTS其他的都没有对测试集进行划分。

**Comment by lartpang** [comment]
@Dreamerswile 你好，PASCAL-S没有训练集。HKU-IS可以按照EGNet的划分方式来看。
我们的方法训练实际上只使用了DUTS的训练集，在DUTS测试集合和其他数据集上进行测试。

**Comment by Dreamerswile** [comment]
非常感谢您的解答，也就是说您目前的方法是只训练的了DUTS数据集，然后对您论文中提到五个数据集进行测试对吗？

**Comment by lartpang** [comment]
@Dreamerswile 是这样的。现有的显著性目标检测方法都是这样的。
