### ISSUE TITLE
SIM moudle is differ from paper

### ISSUE THREAD

**Issue by 1021151558** [lartpang/MINet#15]
SIM moudle is differ from paper,it less a element-wise addition. Why do you change it?

**Comment by 1021151558** [comment]
why do you do it

**Comment by lartpang** [comment]
This is a small deviation in implementation. 
In fact, the identity connection you mentioned is located in the overall model, and I did not put it directly in the SIM, like this line:
https://github.com/lartpang/MINet/blob/master/code/network/MINet.py#L54
