### ISSUE TITLE
To test MINet model on some images do I also need the mask folder?

### ISSUE THREAD

**Issue by Monikshah** [lartpang/MINet#19]
I am trying to use MINet model to extract the salient objects in flicker8k dataset.

**Comment by lartpang** [comment]
@Monikshah 
I have commited a new script in `code/tools` for the inferece without masks in the lastest version.
https://github.com/lartpang/MINet/tree/master/code#if-you-want-to-inference-the-trained-model-on-your-own-dataset

**Comment by Monikshah** [comment]
Thank you very much. I was able to run it in my dataset.
