### ISSUE TITLE
40/5000  Hello, the DUTS-TE of significance map you provided only has 5017 pictures, and there are two pictures missing. Why is that?

### ISSUE THREAD

**Issue by zzzppcc** [lartpang/MINet#23]

**Comment by zzzppcc** [comment]
ILSVRC2012_test_00036002.png and sun_bcogaqperiljqupq.png

**Comment by lartpang** [comment]
@zzzppcc 

Because I found that these images and masks do not correspond: 😸 

![image](https://user-images.githubusercontent.com/26847524/179700391-92e3c4a2-0441-41a9-810a-8f83af829326.png)

**Comment by zzzppcc** [comment]
![image](https://user-images.githubusercontent.com/62326586/180629315-40ca7e03-d434-4123-9082-5bc5e1973f1b.png)
![image](https://user-images.githubusercontent.com/62326586/180629341-c439d250-7ae8-40f5-8b76-31683d361580.png)

**Comment by zzzppcc** [comment]
您好，非常感谢您可以回复我的问题，但是我这边查看确实是正常的mask，那我可能需要对你们的结果进行重新测试了

**Comment by lartpang** [comment]
@zzzppcc
我的数据集是很久之前下载的，可能存在一些小问题。你可以考虑重新生成下。

**Comment by zzzppcc** [comment]
好的，非常感谢您的回答，帮助我解决了很大的问题
