### ISSUE TITLE
您好，纯Windows环境可以运行吗，需要进行哪些额外设置？

### ISSUE THREAD

**Issue by bigtiezhu** [lartpang/MINet#24]

**Comment by lartpang** [comment]
@bigtiezhu 

纯windows环境运行可能最大的问题是路径和apex的编译问题。建议使用wsl2内的linux环境执行。

**Comment by bigtiezhu** [comment]
好的感谢，rtx2060 12g环境在Windows环境下经过两天训练后可以完成，并且可以进行检测，有时间在Linux再进行一下实验

> @bigtiezhu
> 
> 纯windows环境运行可能最大的问题是路径和apex的编译问题。建议使用wsl2内的linux环境执行。
