### ISSUE TITLE
您好，不需要mask进行检测的版本您还会更新吗？

### ISSUE THREAD

**Issue by bigtiezhu** [lartpang/MINet#25]
您在之前的issue提到
“NOTE: Currently, I only released the code to test images which have the paired masks. But it is easy to modify the code in https://github.com/lartpang/MINet/blob/master/code/utils/imgs/create_rgb_datasets_imgs.py and https://github.com/lartpang/MINet/blob/master/code/utils/solver.py to test your images without masks”
请问这个版本还会更新吗，如果不更新，想请您告诉我修改思路，怎么样在无mask下进行检测

**Comment by lartpang** [comment]
@lartpang 

待我检查一下我的代码，更新好了回复您。

**Comment by lartpang** [comment]
@bigtiezhu 

我在`simpler`分支中更新了一个预测脚本，欢迎试用：

https://github.com/lartpang/MINet/blob/simpler/predict.py
