### ISSUE TITLE
DUTS好像少了2张图像

### ISSUE THREAD

**Issue by chiukin** [lartpang/MINet#3]
下载了显著图，发现你的DUTS只有5017张，实际有5019吧，so 把那2张补全下？

**Comment by lartpang** [comment]
> 下载了显著图，发现你的DUTS只有5017张，实际有5019吧，so 把那2张补全下？

原始的DUTS的那两张是存在问题的。我这里将其删除了。这是一个比较常见的处理，很多其他的工作也是这样的呢。

**Comment by chiukin** [comment]
我记得AFNet好像觉得Pas里面有5张有问题，所以删了5张，不知道你觉得有没有必要呢

**Comment by lartpang** [comment]
> 我记得AFNet好像觉得Pas里面有5张有问题，所以删了5张，不知道你觉得有没有必要呢

这一点确实，由于我使用的评估代码是以AFNet的评估代码为基础的，所以我选择了删除这5张。
