### ISSUE TITLE
matting leaves and flowers

### ISSUE THREAD

**Issue by sankexin** [lartpang/MINet#6]
When I go to pick the flowers with leaves, some of the background on the edge of the target cannot be removed. If they are cut off together, the background on the internal space of the target can not be removed. How to solve this problem？
If it can be solved, it is a meaningful thing，thanks for your reply.

**Comment by lartpang** [comment]
I'm sorry to reply so late 🧼 .  

Accurate segmentation for the object, especially the areas near the edges of images with complex backgrounds , is indeed very difficult for the segmentation model based on deep learning (salient object detection, semantic segmentation, instance segmentation, etc.). This is actually one of the reasons why many methods introduce edge information as assistance.

**Comment by lartpang** [comment]
@sankexin 

At present, there is no perfect solution to achieve the perfect separation of the object and background in the image. Although some post-processing methods such as CRF and SegFix can be used, they can only improve the average performance, and some difficult data will still have problems.  This is really very difficult.  Now we can only constantly optimize and improve our method to gradually approach this goal.
