### ISSUE TITLE
is there 2 images missing in DUTS-TE?

### ISSUE THREAD

**Issue by pengqianli** [lartpang/MINet#7]
the provided results on DUTS-TE only contain 5017 images, while the dataset contains 5019 images.
'ILSVRC2012_test_00036002.png' and 'sun_bcogaqperiljqupq.png'.

**Comment by pengqianli** [comment]
thers is a question for me. Can i use the provided model weight files to generate results for comparsion or should i directly use the salient maps provided by the authors?

**Comment by lartpang** [comment]
The most direct way is to use the salient maps provided by us.

The predicted results I provide are consistent with those given in the paper.

**Comment by pengqianli** [comment]
thanks!
