### ISSUE TITLE
Some question about PASCAL-S.

### ISSUE THREAD

**Issue by pengqianli** [lartpang/MINet#9]
您好，现有的模型所提供的结果PASCAL-S上进行测试时，AUC和MaxF往往都是NAN，但是我看的您的论文中MAXF是0.882，请问您是怎么得到这个结果的（我在别的Project中看的有人是直接剔除了没有显著目标的图片，有人则认为应该在完整数据集上进行测试）？（注：我使用的evaluate code就是您提供的那份）

**Comment by lartpang** [comment]
我们使用的是850中的845张，和AFNet中的设定一致。

**Comment by pengqianli** [comment]
感谢您的回复！
